AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Param01:
    Type: String
    Description: 'Param01'
    Default: "example"

Resources:
  BackuperVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: BackuperVPC
        - Key: CreatedBy
          Value: CloudFormationStack
        - Key: App
          Value: Backuper

  BackuperSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: BackuperVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: ""
      Tags:
        - Key: Name
          Value: BackuperSubnet
        - Key: CreatedBy
          Value: CloudFormationStack
        - Key: App
          Value: Backuper

  BackuperSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all trafic
      VpcId: !Ref BackuperVPC
      Tags:
        - Key: Name
          Value: BackuperSG
        - Key: CreatedBy
          Value: CloudFormationStack
        - Key: App
          Value: Backuper

  S3BuckerForBackups:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: backuper-bucket-0123456789
      Tags:
        - Key: Name
          Value: BackuperS3
        - Key: CreatedBy
          Value: CloudFormationStack
        - Key: App
          Value: Backuper

  BackuperComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      # ServiceRole: !Ref AWSServiceLinkedRoleForBatch
      ComputeEnvironmentName: backuper-environment
      # EksConfiguration:
      #   EksClusterArn: !Ref BackuperECSCluster
      #   KubernetesNamespace: "ns-test"
      ComputeResources:
        MaxvCpus: 4
        SecurityGroupIds:
          - !Ref BackuperSecurityGroup
        Type: FARGATE
        Subnets:
          - !Ref BackuperSubnet
      # Tags:
      #   - Key: Name
      #     Value: BackuperComputeEnvironment
      #   - Key: CreatedBy
      #     Value: CloudFormationStack
      #   - Key: App
      #     Value: Backuper
      State: ENABLED


  AWSServiceRoleForBatch:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - batch.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        Path: /
        ManagedPolicyArns:
             - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole
        Tags:
          - Key: Name
            Value: AWSServiceRoleForBatch
          - Key: CreatedBy
            Value: CloudFormationStack
          - Key: App
            Value: Backuper

  AWSServiceLinkedRoleForBatch:
    Type: AWS::IAM::ServiceLinkedRole
    Properties:
      AWSServiceName: batch.amazonaws.com
      Description: Service linked role for AWS Batch



  BackuperECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: BackuperECSCluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
      Tags:
        - Key: Name
          Value: BackuperECSCluster
        - Key: CreatedBy
          Value: CloudFormationStack
        - Key: App
          Value: Backuper