AWSTemplateFormatVersion: "2010-09-09"

Resources:
  S3BuckerForBackups:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: adsf2342343asfsdf
      Tags:
           - Key: Name
             Value: BackuperS3
           - Key: CreatedBy
             Value: CloudFormationStack
