name: Deploy to AWS Cloud Formation

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: eu-central-1
  
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: Backuper
        template: backuper.yaml
        parameter-overrides: >
          awsBackupDestinationBucketName=${{ secrets.AWS_BACKUP_DESTINATION_BUCKET_NAME }}, 
          doPgUser=${{ secrets.DO_PG_USER }}, 
          doKey=${{ secrets.DO_KEY }}, 
          doPgDbname=${{ secrets.DO_PG_DBNAME }}, 
          doPgHost=${{ secrets.DO_PG_HOST }}, 
          doSecret=${{ secrets.DO_SECRET }}, 
          doRegionEndpoint=${{ secrets.DO_REGION_ENDPOINT }}, 
          doPgPort=${{ secrets.DO_PG_PORT }}, 
          doPgPassword=${{ secrets.DO_PG_PASSWORD }}